DROP TABLE SEMI_NORMAL_BOARD;		-- 일반게시글 (FK SEMI_MEMBER, SEMI_NORMAL_BOARD_TYPE)
DROP TABLE SEMI_NORMAL_BOARD_TYPE;	-- 일반게시판 종류 (FK 없음)
DROP TABLE SEMI_NORMAL_BOARD_IMG;	-- 게시글 이미지 (FK SEMI_NORMAL_BOARD)
DROP TABLE SEMI_MEMBER;				-- 회원 (FK 없음)
DROP TABLE SEMI_RECIPE;				-- 레시피 (FK SEMI_MEMBER)
DROP TABLE SEMI_RECIPE_INGREDIENT;	-- 레시피별 요리재료 (FK SEMI_RECIPE, SEMI_INGREDIENT_SPEC) (이 놈이 제일 중요)
DROP TABLE SEMI_INGREDIENT_SPEC;	-- 재료 특징(FK 없음)
DROP TABLE SEMI_RECIPE_BOARD_IMG;	-- 레시피 게시판 이미지(FK SEMI_RECIPE)
DROP TABLE SEMI_BOARD_LIKE;			-- 게시글 좋아요(PFK SEMI_MEMBER, SEMI_NORMAL_BOARD)


CREATE TABLE "SEMI_MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(300)		NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_PW" IS '회원비밀번호';

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_TEL" IS '회원전화번호';

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_ADDRESS" IS '회원주소';

COMMENT ON COLUMN "SEMI_MEMBER"."PROFILE_IMG" IS '프로필이미지';

COMMENT ON COLUMN "SEMI_MEMBER"."ENROLL_DATE" IS '회원가입일';

COMMENT ON COLUMN "SEMI_MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(Y/N)';

COMMENT ON COLUMN "SEMI_MEMBER"."AUTHORITY" IS '권한(1:일반, 2:관리자)';

CREATE TABLE "SEMI_NORMAL_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."BOARD_NO" IS '일반게시글 번호(PK)';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."BOARD_DEL_FL" IS '게시글 삭제여부(Y/N)';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."MEMBER_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD"."BOARD_CODE" IS '일반게시판 종류 코드번호(PK)';

CREATE TABLE "SEMI_NORMAL_BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_TYPE"."BOARD_CODE" IS '일반게시판 종류 코드번호(PK)';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_TYPE"."BOARD_NAME" IS '게시판 이름';

CREATE TABLE "SEMI_NORMAL_BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_IMG"."IMG_NO" IS '이미지번호(PK)';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_IMG"."IMG_PATH" IS '이미지 요청 경로';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_IMG"."IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_IMG"."IMG_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_IMG"."IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "SEMI_NORMAL_BOARD_IMG"."BOARD_NO" IS '일반게시글 번호(PK)';

CREATE TABLE "SEMI_RECIPE_BOARD_IMG" (
	"RECIPE_IMG_NO"	NUMBER		NOT NULL,
	"RECIPE_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"RECIPE_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"RECIPE_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"RECIPE_IMG_ORDER"	NUMBER		NULL,
	"RECIPE_VIDEO_URL"	NVARCHAR2(200)		NULL,
	"RECIPE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SEMI_RECIPE_BOARD_IMG"."RECIPE_IMG_NO" IS '레시피 이미지 번호(PK)';

COMMENT ON COLUMN "SEMI_RECIPE_BOARD_IMG"."RECIPE_IMG_PATH" IS '레시피 이미지 요청 경로';

COMMENT ON COLUMN "SEMI_RECIPE_BOARD_IMG"."RECIPE_IMG_ORIGINAL_NAME" IS '레시피 이미지 원본명';

COMMENT ON COLUMN "SEMI_RECIPE_BOARD_IMG"."RECIPE_IMG_RENAME" IS '레시피 이미지 변경명';

COMMENT ON COLUMN "SEMI_RECIPE_BOARD_IMG"."RECIPE_IMG_ORDER" IS '레시피 이미지 순서';

COMMENT ON COLUMN "SEMI_RECIPE_BOARD_IMG"."RECIPE_VIDEO_URL" IS '레시피 영상 URL';

COMMENT ON COLUMN "SEMI_RECIPE_BOARD_IMG"."RECIPE_NO" IS '레시피번호(PK)';

CREATE TABLE "SEMI_INGREDIENT_SPEC" (
	"INGREDIENT_NO"	NUMBER		NOT NULL,
	"INGREDIENT_NAME"	NVARCHAR2(50)		NOT NULL,
	"INGREDIENT_TYPE"	NUMBER		NOT NULL,
	"PRICE_PER_INGRED"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SEMI_INGREDIENT_SPEC"."INGREDIENT_NO" IS '재료 번호(PK)';

COMMENT ON COLUMN "SEMI_INGREDIENT_SPEC"."INGREDIENT_NAME" IS '재료명';

COMMENT ON COLUMN "SEMI_INGREDIENT_SPEC"."INGREDIENT_TYPE" IS '재료가격(원데이터)';

COMMENT ON COLUMN "SEMI_INGREDIENT_SPEC"."PRICE_PER_INGRED" IS '단위당가격(g/원)';

CREATE TABLE "SEMI_RECIPE" (
	"RECIPE_NO"	NUMBER		NOT NULL,
	"RECIPE_NAME"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SEMI_RECIPE"."RECIPE_NO" IS '레시피번호(PK)';

COMMENT ON COLUMN "SEMI_RECIPE"."RECIPE_NAME" IS '레시피 이름';

COMMENT ON COLUMN "SEMI_RECIPE"."MEMBER_NO" IS '회원번호(PK)';

CREATE TABLE "SEMI_RECIPE_INGREDIENT" (
	"RECIPE_ING_NO"	NUMBER		NOT NULL,
	"INGRED_VOLUME"	NUMBER		NOT NULL,
	"RECIPE_LIKE_NO"	NUMBER	DEFAULT 0	NOT NULL,
	"RECIPE_NO"	NUMBER		NOT NULL,
	"INGREDIENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SEMI_RECIPE_INGREDIENT"."RECIPE_ING_NO" IS '레시피별 요리재료 번호(PK)';

COMMENT ON COLUMN "SEMI_RECIPE_INGREDIENT"."INGRED_VOLUME" IS '재료용량(각 재료당 필요용량)';

COMMENT ON COLUMN "SEMI_RECIPE_INGREDIENT"."RECIPE_LIKE_NO" IS '레시피 좋아요 수';

COMMENT ON COLUMN "SEMI_RECIPE_INGREDIENT"."RECIPE_NO" IS '레시피번호(PK)';

COMMENT ON COLUMN "SEMI_RECIPE_INGREDIENT"."INGREDIENT_NO" IS '재료 번호(PK)';

CREATE TABLE "SEMI_BOARD_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SEMI_BOARD_LIKE"."MEMBER_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "SEMI_BOARD_LIKE"."BOARD_NO" IS '일반게시글 번호(PK)';


----- PK ------------------------------------------------------------------------

ALTER TABLE "SEMI_MEMBER" ADD CONSTRAINT "PK_SEMI_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "SEMI_NORMAL_BOARD" ADD CONSTRAINT "PK_SEMI_NORMAL_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "SEMI_NORMAL_BOARD_TYPE" ADD CONSTRAINT "PK_SEMI_NORMAL_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "SEMI_NORMAL_BOARD_IMG" ADD CONSTRAINT "PK_SEMI_NORMAL_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "SEMI_RECIPE_BOARD_IMG" ADD CONSTRAINT "PK_SEMI_RECIPE_BOARD_IMG" PRIMARY KEY (
	"RECIPE_IMG_NO"
);

ALTER TABLE "SEMI_INGREDIENT_SPEC" ADD CONSTRAINT "PK_SEMI_INGREDIENT_SPEC" PRIMARY KEY (
	"INGREDIENT_NO"
);

ALTER TABLE "SEMI_RECIPE" ADD CONSTRAINT "PK_SEMI_RECIPE" PRIMARY KEY (
	"RECIPE_NO"
);

ALTER TABLE "SEMI_RECIPE_INGREDIENT" ADD CONSTRAINT "PK_SEMI_RECIPE_INGREDIENT" PRIMARY KEY (
	"RECIPE_ING_NO"
);

ALTER TABLE "SEMI_BOARD_LIKE" ADD CONSTRAINT "PK_SEMI_BOARD_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"BOARD_NO"
);

ALTER TABLE "SEMI_NORMAL_BOARD" ADD CONSTRAINT "FK_SEMI_MEMBER_TO_SEMI_NORMAL_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "SEMI_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "SEMI_NORMAL_BOARD" ADD CONSTRAINT "FK_SEMI_NORMAL_BOARD_TYPE_TO_SEMI_NORMAL_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "SEMI_NORMAL_BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "SEMI_NORMAL_BOARD_IMG" ADD CONSTRAINT "FK_SEMI_NORMAL_BOARD_TO_SEMI_NORMAL_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "SEMI_NORMAL_BOARD" (
	"BOARD_NO"
);

ALTER TABLE "SEMI_RECIPE_BOARD_IMG" ADD CONSTRAINT "FK_SEMI_RECIPE_TO_SEMI_RECIPE_BOARD_IMG_1" FOREIGN KEY (
	"RECIPE_NO"
)
REFERENCES "SEMI_RECIPE" (
	"RECIPE_NO"
);

ALTER TABLE "SEMI_RECIPE" ADD CONSTRAINT "FK_SEMI_MEMBER_TO_SEMI_RECIPE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "SEMI_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "SEMI_RECIPE_INGREDIENT" ADD CONSTRAINT "FK_SEMI_RECIPE_TO_SEMI_RECIPE_INGREDIENT_1" FOREIGN KEY (
	"RECIPE_NO"
)
REFERENCES "SEMI_RECIPE" (
	"RECIPE_NO"
);

ALTER TABLE "SEMI_RECIPE_INGREDIENT" ADD CONSTRAINT "FK_SEMI_INGREDIENT_SPEC_TO_SEMI_RECIPE_INGREDIENT_1" FOREIGN KEY (
	"INGREDIENT_NO"
)
REFERENCES "SEMI_INGREDIENT_SPEC" (
	"INGREDIENT_NO"
);

ALTER TABLE "SEMI_BOARD_LIKE" ADD CONSTRAINT "FK_SEMI_MEMBER_TO_SEMI_BOARD_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "SEMI_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "SEMI_BOARD_LIKE" ADD CONSTRAINT "FK_SEMI_NORMAL_BOARD_TO_SEMI_BOARD_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "SEMI_NORMAL_BOARD" (
	"BOARD_NO"
);

------ 시퀀스 생성 -------------------------------------------------------------
CREATE SEQUENCE SEQ_SEMI_INGREDIENT_SPEC NOCACHE;
CREATE SEQUENCE SEQ_SEMI_MEMBER NOCACHE;
CREATE SEQUENCE SEQ_SEMI_NORMAL_BOARD NOCACHE;
CREATE SEQUENCE SEQ_SEMI_NORMAL_BOARD_IMG NOCACHE;
CREATE SEQUENCE SEQ_SEMI_NORMAL_BOARD_TYPE NOCACHE;
CREATE SEQUENCE SEQ_SEMI_RECIPE NOCACHE;
CREATE SEQUENCE SEQ_SEMI_RECIPE_BOARD_IMG NOCACHE;
CREATE SEQUENCE SEQ_SEMI_RECIPE_INGREDIENT NOCACHE;

------ 테스트용 SQL 구문 ----------------------------------------------------

------ SEMI_MEMBER (FK 없음) ------
SELECT * FROM SEMI_MEMBER;

INSERT INTO SEMI_MEMBER
VALUES (SEQ_SEMI_MEMBER.NEXTVAL, 'user01@kh.or.kr', '암호화된 비밀번호', '홍길동', '유저일', '01011112222', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO SEMI_MEMBER
VALUES (SEQ_SEMI_MEMBER.NEXTVAL, 'user02@kh.or.kr', '암호화된 비밀번호', '홍홍홍', '유저이', '01022223333', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO SEMI_MEMBER
VALUES (SEQ_SEMI_MEMBER.NEXTVAL, 'user03@kh.or.kr', '암호화된 비밀번호', '길길길', '유저삼', '01012345678', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

SELECT * FROM SEMI_MEMBER;

COMMIT;

----- 일반게시판 종류 (FK 없음) -----
SELECT * FROM SEMI_NORMAL_BOARD_TYPE;

INSERT INTO SEMI_NORMAL_BOARD_TYPE
VALUES (SEQ_SEMI_NORMAL_BOARD_TYPE.NEXTVAL, '공지게시판');

INSERT INTO SEMI_NORMAL_BOARD_TYPE
VALUES (SEQ_SEMI_NORMAL_BOARD_TYPE.NEXTVAL, '자유게시판');

INSERT INTO SEMI_NORMAL_BOARD_TYPE
VALUES (SEQ_SEMI_NORMAL_BOARD_TYPE.NEXTVAL, '공동 구매 모집');

INSERT INTO SEMI_NORMAL_BOARD_TYPE
VALUES (SEQ_SEMI_NORMAL_BOARD_TYPE.NEXTVAL, '자취요리 레시피 공유');

SELECT * FROM SEMI_NORMAL_BOARD_TYPE;

COMMIT;

----- 재료 특징 (FK 없음) -----
SELECT * FROM SEMI_INGREDIENT_SPEC;

INSERT INTO SEMI_INGREDIENT_SPEC
VALUES (SEQ_SEMI_INGREDIENT_SPEC.NEXTVAL, '당근', 10000, 2000);

INSERT INTO SEMI_INGREDIENT_SPEC
VALUES (SEQ_SEMI_INGREDIENT_SPEC.NEXTVAL, '공기밥', 3000, 333);

INSERT INTO SEMI_INGREDIENT_SPEC
VALUES (SEQ_SEMI_INGREDIENT_SPEC.NEXTVAL, '계란', 10000, 500);

INSERT INTO SEMI_INGREDIENT_SPEC
VALUES (SEQ_SEMI_INGREDIENT_SPEC.NEXTVAL, '닭', 10000, 1500);

INSERT INTO SEMI_INGREDIENT_SPEC
VALUES (SEQ_SEMI_INGREDIENT_SPEC.NEXTVAL, '돼지', 15000, 1100);

INSERT INTO SEMI_INGREDIENT_SPEC
VALUES (SEQ_SEMI_INGREDIENT_SPEC.NEXTVAL, '소', 10000, 3000);

SELECT * FROM SEMI_INGREDIENT_SPEC;

COMMIT;

----- 일반게시글 (FK MEMBER_NO 8행, BOARD_CODE 9행) -----
SELECT * FROM SEMI_NORMAL_BOARD;

INSERT INTO SEMI_NORMAL_BOARD
VALUES(SEQ_SEMI_NORMAL_BOARD.NEXTVAL, '게시글 제목1', '게시글 내용1', DEFAULT, NULL, DEFAULT, DEFAULT, 1, 2);

INSERT INTO SEMI_NORMAL_BOARD
VALUES(SEQ_SEMI_NORMAL_BOARD.NEXTVAL, '게시글 제목2', '게시글 내용2', DEFAULT, NULL, DEFAULT, DEFAULT, 1, 1);

INSERT INTO SEMI_NORMAL_BOARD
VALUES(SEQ_SEMI_NORMAL_BOARD.NEXTVAL, '게시글 제목3', '게시글 내용3', DEFAULT, NULL, DEFAULT, DEFAULT, 2, 1);

INSERT INTO SEMI_NORMAL_BOARD
VALUES(SEQ_SEMI_NORMAL_BOARD.NEXTVAL, '게시글 제목4', '게시글 내용4', DEFAULT, NULL, DEFAULT, DEFAULT, 1, 3);

INSERT INTO SEMI_NORMAL_BOARD
VALUES(SEQ_SEMI_NORMAL_BOARD.NEXTVAL, '게시글 제목5', '게시글 내용5', DEFAULT, NULL, DEFAULT, DEFAULT, 1, 1);

INSERT INTO SEMI_NORMAL_BOARD
VALUES(SEQ_SEMI_NORMAL_BOARD.NEXTVAL, '게시글 제목6', '게시글 내용6', DEFAULT, NULL, DEFAULT, DEFAULT, 2, 2);

SELECT * FROM SEMI_NORMAL_BOARD;

COMMIT;

----- 레시피 (FK MEMBER_NO 3행) -----
SELECT * FROM SEMI_RECIPE;

INSERT INTO SEMI_RECIPE
VALUES (SEQ_SEMI_RECIPE.NEXTVAL, '간장계란밥', 1);

INSERT INTO SEMI_RECIPE
VALUES (SEQ_SEMI_RECIPE.NEXTVAL, '라면밥', 1);

INSERT INTO SEMI_RECIPE
VALUES (SEQ_SEMI_RECIPE.NEXTVAL, '닭갈비 볶음밥', 2);

SELECT * FROM SEMI_RECIPE;

COMMIT;

----- 레시피별 요리재료 (FK RECIPE_NO 4행, INGREDIENT_NO 5행) -----
SELECT * FROM SEMI_RECIPE_INGREDIENT;
--- (레시피명, 재료용량, 좋아요 수, 레시피번호, 재료번호)

INSERT INTO SEMI_RECIPE_INGREDIENT
VALUES (SEQ_SEMI_RECIPE_INGREDIENT.NEXTVAL, 3, DEFAULT, 1, 1);

INSERT INTO SEMI_RECIPE_INGREDIENT
VALUES (SEQ_SEMI_RECIPE_INGREDIENT.NEXTVAL, 4, DEFAULT, 1, 2);

INSERT INTO SEMI_RECIPE_INGREDIENT
VALUES (SEQ_SEMI_RECIPE_INGREDIENT.NEXTVAL, 2, DEFAULT, 1, 6);

SELECT * FROM SEMI_RECIPE_INGREDIENT;

COMMIT;

----- 게시글 이미지(일단 생략) -----

----- 레시피 게시판 이미지 (일단 생략) -----

----- 게시글 좋아요(맨 마지막에) -----




----- 레시피별 요리재료 TABLE에서 RECIPE_NO = 1(RECIPE_NAME = 간장계란밥) 의 재료 및 필요용량, 가격 가져오기
SELECT sr.RECIPE_NAME "요리명", sis.INGREDIENT_NAME "재료명", sri.INGRED_VOLUME "필요용량", sis.PRICE_PER_INGRED "단위당 가격"
FROM SEMI_RECIPE_INGREDIENT sri
JOIN SEMI_RECIPE sr ON(sr.RECIPE_NO = sri.RECIPE_NO)
JOIN SEMI_INGREDIENT_SPEC sis ON(sri.INGREDIENT_NO = sis.INGREDIENT_NO)
WHERE sri.RECIPE_NO = 1;


